/* eslint-disable @typescript-eslint/member-ordering */
/**
 * This file was automatically generated by `bwcx-api-client`.
 * DO NOT MODIFY IT BY HAND.
 */

import { AllowedRequestMethod, IBwcxApiRequestAdaptorArgs, AbstractResponseParser } from 'bwcx-api-client';
import { configure as configureUrlcat } from 'urlcat-fork';
import { GetGlobalConfigResDTO, UpdateGlobalConfigReqDTO } from '../modules/global-config/global-config.dto';
import { RegisterAdminReqDTO, LoginAdminWithUserNameReqDTO, GetSessionResDTO, UpdateAdminAvatarReqDTO, GetAllAdminsListResDTO, UpdateAdminRoleReqDTO, ResetAdminPasswordReqDTO, DeleteAdminReqDTO } from '../modules/admin/admin.dto';
import { DemoGetReqDTO, DemoGetRespDTO } from '../modules/demo/demo.dto';
import { GetHomeDataResDTO, GetHomeNewsResDTO } from '../modules/home/home.dto';
import { GetMediaListReqDTO, GetMediaListResDTO, UploadMediaReqDTO, MediaDetailResDTO, GetMediaByIdReqDTO, UpdateMediaReqDTO, DeleteMediaReqDTO, InitChunkUploadReqDTO, InitChunkUploadResDTO, UploadChunkReqDTO, UploadChunkResDTO, CompleteChunkUploadReqDTO, CompleteChunkUploadResDTO } from '../modules/media/media.dto';
import { CreateNewsReqDTO, UpdateNewsReqDTO, DeleteNewsReqDTO, GetNewsReqDTO, GetNewsDetailResDTO, GetAllNewsReqDTO, GetAllNewsResDTO, GetPublishedNewsListReqDTO, GetPublishedNewsListResDTO } from '../modules/news/news.dto';
import { CreateProjectReqDTO, UpdateProjectReqDTO, DeleteProjectReqDTO, GetProjectReqDTO, GetProjectDetailResDTO, GetAllProjectsReqDTO, GetAllProjectsResDTO } from '../modules/project/project.dto';
import { GetOverviewStatsResDTO, GetDailyViewStatsReqDTO, GetDailyViewStatsResDTO, GetAllPageViewStatsResDTO } from '../modules/stats/stats.dto';

const urlcat = configureUrlcat({ arrayFormat: 'repeat' });

export class ApiClient<T = undefined> {
  private readonly _r: (args: IBwcxApiRequestAdaptorArgs<T>) => Promise<any>;
  private readonly _rp: AbstractResponseParser;

  public constructor(
    requestAdapter: { request: (args: IBwcxApiRequestAdaptorArgs<T>) => Promise<any> },
    responseParser: AbstractResponseParser,
  ) {
    this._r = requestAdapter.request;
    this._rp = responseParser;
  }

  /**
   * 获取全局配置
   *
   * @param {null} req The request data (compatible with ReqDTO).
   * @param {T} opts Extra request options.
   * @returns {GetGlobalConfigResDTO} The response data (RespDTO).
   */
  public async getGlobalConfig(req?: null, opts?: T): Promise<GetGlobalConfigResDTO> {
    return this._r(this._rArgs.a(req, opts)).then((resp) => this._rp.pat(GetGlobalConfigResDTO, resp));
  }

  /**
   * 更新全局配置
   *
   * @param {UpdateGlobalConfigReqDTO} req The request data (compatible with ReqDTO).
   * @param {T} opts Extra request options.
   * @returns {null} The response data (RespDTO).
   */
  public async updateGlobalConfig(req: UpdateGlobalConfigReqDTO, opts?: T): Promise<null> {
    return this._r(this._rArgs.b(req, opts)).then((resp) => this._rp.pat(null, resp));
  }

  /**
   * 管理员注册
   *
   * @param {RegisterAdminReqDTO} req The request data (compatible with ReqDTO).
   * @param {T} opts Extra request options.
   * @returns {null} The response data (RespDTO).
   */
  public async register(req: RegisterAdminReqDTO, opts?: T): Promise<null> {
    return this._r(this._rArgs.c(req, opts)).then((resp) => this._rp.pat(null, resp));
  }

  /**
   * 管理员登录
   *
   * @param {LoginAdminWithUserNameReqDTO} req The request data (compatible with ReqDTO).
   * @param {T} opts Extra request options.
   * @returns {null} The response data (RespDTO).
   */
  public async login(req: LoginAdminWithUserNameReqDTO, opts?: T): Promise<null> {
    return this._r(this._rArgs.d(req, opts)).then((resp) => this._rp.pat(null, resp));
  }

  /**
   * 管理员登出
   *
   * @param {null} req The request data (compatible with ReqDTO).
   * @param {T} opts Extra request options.
   * @returns {null} The response data (RespDTO).
   */
  public async logout(req?: null, opts?: T): Promise<null> {
    return this._r(this._rArgs.e(req, opts)).then((resp) => this._rp.pat(null, resp));
  }

  /**
   * 获取管理员会话信息
   *
   * @param {null} req The request data (compatible with ReqDTO).
   * @param {T} opts Extra request options.
   * @returns {GetSessionResDTO} The response data (RespDTO).
   */
  public async getSession(req?: null, opts?: T): Promise<GetSessionResDTO> {
    return this._r(this._rArgs.f(req, opts)).then((resp) => this._rp.pat(GetSessionResDTO, resp));
  }

  /**
   * 更新管理员头像
   *
   * @param {UpdateAdminAvatarReqDTO} req The request data (compatible with ReqDTO).
   * @param {T} opts Extra request options.
   * @returns {null} The response data (RespDTO).
   */
  public async updateAdminAvatar(req: UpdateAdminAvatarReqDTO, opts?: T): Promise<null> {
    return this._r(this._rArgs.g(req, opts)).then((resp) => this._rp.pat(null, resp));
  }

  /**
   * 获取所有管理员
   *
   * @param {null} req The request data (compatible with ReqDTO).
   * @param {T} opts Extra request options.
   * @returns {GetAllAdminsListResDTO} The response data (RespDTO).
   */
  public async getAllAdmins(req?: null, opts?: T): Promise<GetAllAdminsListResDTO> {
    return this._r(this._rArgs.h(req, opts)).then((resp) => this._rp.pat(GetAllAdminsListResDTO, resp));
  }

  /**
   * 更新管理员角色
   *
   * @param {UpdateAdminRoleReqDTO} req The request data (compatible with ReqDTO).
   * @param {T} opts Extra request options.
   * @returns {null} The response data (RespDTO).
   */
  public async updateAdminRole(req: UpdateAdminRoleReqDTO, opts?: T): Promise<null> {
    return this._r(this._rArgs.i(req, opts)).then((resp) => this._rp.pat(null, resp));
  }

  /**
   * 重置管理员密码
   *
   * @param {ResetAdminPasswordReqDTO} req The request data (compatible with ReqDTO).
   * @param {T} opts Extra request options.
   * @returns {null} The response data (RespDTO).
   */
  public async resetAdminPassword(req: ResetAdminPasswordReqDTO, opts?: T): Promise<null> {
    return this._r(this._rArgs.j(req, opts)).then((resp) => this._rp.pat(null, resp));
  }

  /**
   * 删除管理员
   *
   * @param {DeleteAdminReqDTO} req The request data (compatible with ReqDTO).
   * @param {T} opts Extra request options.
   * @returns {null} The response data (RespDTO).
   */
  public async deleteAdmin(req: DeleteAdminReqDTO, opts?: T): Promise<null> {
    return this._r(this._rArgs.k(req, opts)).then((resp) => this._rp.pat(null, resp));
  }

  /**
   * 一个示例接口
   *
   * @param {DemoGetReqDTO} req The request data (compatible with ReqDTO).
   * @param {T} opts Extra request options.
   * @returns {DemoGetRespDTO} The response data (RespDTO).
   */
  public async demoGet(req: DemoGetReqDTO, opts?: T): Promise<DemoGetRespDTO> {
    return this._r(this._rArgs.l(req, opts)).then((resp) => this._rp.pat(DemoGetRespDTO, resp));
  }

  /**
   * 获取首页数据
   *
   * @param {null} req The request data (compatible with ReqDTO).
   * @param {T} opts Extra request options.
   * @returns {GetHomeDataResDTO} The response data (RespDTO).
   */
  public async getHomeData(req?: null, opts?: T): Promise<GetHomeDataResDTO> {
    return this._r(this._rArgs.m(req, opts)).then((resp) => this._rp.pat(GetHomeDataResDTO, resp));
  }

  /**
   * 获取首页展示新闻
   *
   * @param {null} req The request data (compatible with ReqDTO).
   * @param {T} opts Extra request options.
   * @returns {GetHomeNewsResDTO} The response data (RespDTO).
   */
  public async getHomeNews(req?: null, opts?: T): Promise<GetHomeNewsResDTO> {
    return this._r(this._rArgs.n(req, opts)).then((resp) => this._rp.pat(GetHomeNewsResDTO, resp));
  }

  /**
   * 获取媒体列表
   *
   * @param {GetMediaListReqDTO} req The request data (compatible with ReqDTO).
   * @param {T} opts Extra request options.
   * @returns {GetMediaListResDTO} The response data (RespDTO).
   */
  public async getMediaList(req: GetMediaListReqDTO, opts?: T): Promise<GetMediaListResDTO> {
    return this._r(this._rArgs.o(req, opts)).then((resp) => this._rp.pat(GetMediaListResDTO, resp));
  }

  /**
   * 上传媒体文件
   *
   * @param {UploadMediaReqDTO} req The request data (compatible with ReqDTO).
   * @param {T} opts Extra request options.
   * @returns {MediaDetailResDTO} The response data (RespDTO).
   */
  public async uploadMedia(req: UploadMediaReqDTO, opts?: T): Promise<MediaDetailResDTO> {
    return this._r(this._rArgs.p(req, opts)).then((resp) => this._rp.pat(MediaDetailResDTO, resp));
  }

  /**
   * 获取媒体详情
   *
   * @param {GetMediaByIdReqDTO} req The request data (compatible with ReqDTO).
   * @param {T} opts Extra request options.
   * @returns {MediaDetailResDTO} The response data (RespDTO).
   */
  public async getMediaById(req: GetMediaByIdReqDTO, opts?: T): Promise<MediaDetailResDTO> {
    return this._r(this._rArgs.q(req, opts)).then((resp) => this._rp.pat(MediaDetailResDTO, resp));
  }

  /**
   * 更新媒体信息
   *
   * @param {UpdateMediaReqDTO} req The request data (compatible with ReqDTO).
   * @param {T} opts Extra request options.
   * @returns {null} The response data (RespDTO).
   */
  public async updateMedia(req: UpdateMediaReqDTO, opts?: T): Promise<null> {
    return this._r(this._rArgs.r(req, opts)).then((resp) => this._rp.pat(null, resp));
  }

  /**
   * 删除媒体文件
   *
   * @param {DeleteMediaReqDTO} req The request data (compatible with ReqDTO).
   * @param {T} opts Extra request options.
   * @returns {null} The response data (RespDTO).
   */
  public async deleteMedia(req: DeleteMediaReqDTO, opts?: T): Promise<null> {
    return this._r(this._rArgs.s(req, opts)).then((resp) => this._rp.pat(null, resp));
  }

  /**
   * 初始化分片上传
   *
   * @param {InitChunkUploadReqDTO} req The request data (compatible with ReqDTO).
   * @param {T} opts Extra request options.
   * @returns {InitChunkUploadResDTO} The response data (RespDTO).
   */
  public async initChunkUpload(req: InitChunkUploadReqDTO, opts?: T): Promise<InitChunkUploadResDTO> {
    return this._r(this._rArgs.t(req, opts)).then((resp) => this._rp.pat(InitChunkUploadResDTO, resp));
  }

  /**
   * 上传分片
   *
   * @param {UploadChunkReqDTO} req The request data (compatible with ReqDTO).
   * @param {T} opts Extra request options.
   * @returns {UploadChunkResDTO} The response data (RespDTO).
   */
  public async uploadChunk(req: UploadChunkReqDTO, opts?: T): Promise<UploadChunkResDTO> {
    return this._r(this._rArgs.u(req, opts)).then((resp) => this._rp.pat(UploadChunkResDTO, resp));
  }

  /**
   * 完成分片上传
   *
   * @param {CompleteChunkUploadReqDTO} req The request data (compatible with ReqDTO).
   * @param {T} opts Extra request options.
   * @returns {CompleteChunkUploadResDTO} The response data (RespDTO).
   */
  public async completeChunkUpload(req: CompleteChunkUploadReqDTO, opts?: T): Promise<CompleteChunkUploadResDTO> {
    return this._r(this._rArgs.v(req, opts)).then((resp) => this._rp.pat(CompleteChunkUploadResDTO, resp));
  }

  /**
   * 创建新闻
   *
   * @param {CreateNewsReqDTO} req The request data (compatible with ReqDTO).
   * @param {T} opts Extra request options.
   * @returns {null} The response data (RespDTO).
   */
  public async createNews(req: CreateNewsReqDTO, opts?: T): Promise<null> {
    return this._r(this._rArgs.w(req, opts)).then((resp) => this._rp.pat(null, resp));
  }

  /**
   * 更新新闻
   *
   * @param {UpdateNewsReqDTO} req The request data (compatible with ReqDTO).
   * @param {T} opts Extra request options.
   * @returns {null} The response data (RespDTO).
   */
  public async updateNews(req: UpdateNewsReqDTO, opts?: T): Promise<null> {
    return this._r(this._rArgs.x(req, opts)).then((resp) => this._rp.pat(null, resp));
  }

  /**
   * 删除新闻
   *
   * @param {DeleteNewsReqDTO} req The request data (compatible with ReqDTO).
   * @param {T} opts Extra request options.
   * @returns {null} The response data (RespDTO).
   */
  public async deleteNews(req: DeleteNewsReqDTO, opts?: T): Promise<null> {
    return this._r(this._rArgs.y(req, opts)).then((resp) => this._rp.pat(null, resp));
  }

  /**
   * 获取新闻详情（管理员用）
   *
   * @param {GetNewsReqDTO} req The request data (compatible with ReqDTO).
   * @param {T} opts Extra request options.
   * @returns {GetNewsDetailResDTO} The response data (RespDTO).
   */
  public async getNews(req: GetNewsReqDTO, opts?: T): Promise<GetNewsDetailResDTO> {
    return this._r(this._rArgs.z(req, opts)).then((resp) => this._rp.pat(GetNewsDetailResDTO, resp));
  }

  /**
   * 获取已发布新闻详情（普通用户用）
   *
   * @param {GetNewsReqDTO} req The request data (compatible with ReqDTO).
   * @param {T} opts Extra request options.
   * @returns {GetNewsDetailResDTO} The response data (RespDTO).
   */
  public async getPublishedNews(req: GetNewsReqDTO, opts?: T): Promise<GetNewsDetailResDTO> {
    return this._r(this._rArgs.aa(req, opts)).then((resp) => this._rp.pat(GetNewsDetailResDTO, resp));
  }

  /**
   * 获取所有新闻列表（管理员用）
   *
   * @param {GetAllNewsReqDTO} req The request data (compatible with ReqDTO).
   * @param {T} opts Extra request options.
   * @returns {GetAllNewsResDTO} The response data (RespDTO).
   */
  public async getAllNews(req: GetAllNewsReqDTO, opts?: T): Promise<GetAllNewsResDTO> {
    return this._r(this._rArgs.ab(req, opts)).then((resp) => this._rp.pat(GetAllNewsResDTO, resp));
  }

  /**
   * 分页获取已发布新闻列表
   *
   * @param {GetPublishedNewsListReqDTO} req The request data (compatible with ReqDTO).
   * @param {T} opts Extra request options.
   * @returns {GetPublishedNewsListResDTO} The response data (RespDTO).
   */
  public async getPublishedNewsList(req: GetPublishedNewsListReqDTO, opts?: T): Promise<GetPublishedNewsListResDTO> {
    return this._r(this._rArgs.ac(req, opts)).then((resp) => this._rp.pat(GetPublishedNewsListResDTO, resp));
  }

  /**
   * 创建项目
   *
   * @param {CreateProjectReqDTO} req The request data (compatible with ReqDTO).
   * @param {T} opts Extra request options.
   * @returns {null} The response data (RespDTO).
   */
  public async createProject(req: CreateProjectReqDTO, opts?: T): Promise<null> {
    return this._r(this._rArgs.ad(req, opts)).then((resp) => this._rp.pat(null, resp));
  }

  /**
   * 更新项目
   *
   * @param {UpdateProjectReqDTO} req The request data (compatible with ReqDTO).
   * @param {T} opts Extra request options.
   * @returns {null} The response data (RespDTO).
   */
  public async updateProject(req: UpdateProjectReqDTO, opts?: T): Promise<null> {
    return this._r(this._rArgs.ae(req, opts)).then((resp) => this._rp.pat(null, resp));
  }

  /**
   * 删除项目
   *
   * @param {DeleteProjectReqDTO} req The request data (compatible with ReqDTO).
   * @param {T} opts Extra request options.
   * @returns {null} The response data (RespDTO).
   */
  public async deleteProject(req: DeleteProjectReqDTO, opts?: T): Promise<null> {
    return this._r(this._rArgs.af(req, opts)).then((resp) => this._rp.pat(null, resp));
  }

  /**
   * 获取项目详情
   *
   * @param {GetProjectReqDTO} req The request data (compatible with ReqDTO).
   * @param {T} opts Extra request options.
   * @returns {GetProjectDetailResDTO} The response data (RespDTO).
   */
  public async getProject(req: GetProjectReqDTO, opts?: T): Promise<GetProjectDetailResDTO> {
    return this._r(this._rArgs.ag(req, opts)).then((resp) => this._rp.pat(GetProjectDetailResDTO, resp));
  }

  /**
   * 获取所有项目列表（管理员用）
   *
   * @param {GetAllProjectsReqDTO} req The request data (compatible with ReqDTO).
   * @param {T} opts Extra request options.
   * @returns {GetAllProjectsResDTO} The response data (RespDTO).
   */
  public async getAllProjects(req: GetAllProjectsReqDTO, opts?: T): Promise<GetAllProjectsResDTO> {
    return this._r(this._rArgs.ah(req, opts)).then((resp) => this._rp.pat(GetAllProjectsResDTO, resp));
  }

  /**
   * 获取概览统计数据
   *
   * @param {null} req The request data (compatible with ReqDTO).
   * @param {T} opts Extra request options.
   * @returns {GetOverviewStatsResDTO} The response data (RespDTO).
   */
  public async getOverviewStats(req?: null, opts?: T): Promise<GetOverviewStatsResDTO> {
    return this._r(this._rArgs.ai(req, opts)).then((resp) => this._rp.pat(GetOverviewStatsResDTO, resp));
  }

  /**
   * 获取每日访问统计
   *
   * @param {GetDailyViewStatsReqDTO} req The request data (compatible with ReqDTO).
   * @param {T} opts Extra request options.
   * @returns {GetDailyViewStatsResDTO} The response data (RespDTO).
   */
  public async getDailyViewStats(req: GetDailyViewStatsReqDTO, opts?: T): Promise<GetDailyViewStatsResDTO> {
    return this._r(this._rArgs.aj(req, opts)).then((resp) => this._rp.pat(GetDailyViewStatsResDTO, resp));
  }

  /**
   * 获取所有页面访问统计
   *
   * @param {null} req The request data (compatible with ReqDTO).
   * @param {T} opts Extra request options.
   * @returns {GetAllPageViewStatsResDTO} The response data (RespDTO).
   */
  public async getAllPageViewStats(req?: null, opts?: T): Promise<GetAllPageViewStatsResDTO> {
    return this._r(this._rArgs.ak(req, opts)).then((resp) => this._rp.pat(GetAllPageViewStatsResDTO, resp));
  }

  private _rArgs = {
    a: (req: null, opts?: any) => {
      return {
        method: 'POST' as AllowedRequestMethod,
        url: this._uf('/api/getGlobalConfig', {
          param: {},
          query: {},
        }),
        data: {},
        extraOpts: opts,
        metadata: {
          name: 'getGlobalConfig',
          method: 'POST',
          path: '/api/getGlobalConfig',
          req: null as null,
          resp: GetGlobalConfigResDTO,
        },
      };
    },
    b: (req: UpdateGlobalConfigReqDTO, opts?: any) => {
      return {
        method: 'POST' as AllowedRequestMethod,
        url: this._uf('/api/updateGlobalConfig', {
          param: {},
          query: {},
        }),
        data: {
          title: req.title,
          slogan: req.slogan,
          description: req.description,
          logoId: req.logoId,
          homeNewsPreviewIds: req.homeNewsPreviewIds,
          homeProjectsPreviewIds: req.homeProjectsPreviewIds,
        },
        extraOpts: opts,
        metadata: {
          name: 'updateGlobalConfig',
          method: 'POST',
          path: '/api/updateGlobalConfig',
          req: UpdateGlobalConfigReqDTO,
          resp: null as null,
        },
      };
    },
    c: (req: RegisterAdminReqDTO, opts?: any) => {
      return {
        method: 'POST' as AllowedRequestMethod,
        url: this._uf('/api/register', {
          param: {},
          query: {},
        }),
        data: {
          username: req.username,
          password: req.password,
        },
        extraOpts: opts,
        metadata: {
          name: 'register',
          method: 'POST',
          path: '/api/register',
          req: RegisterAdminReqDTO,
          resp: null as null,
        },
      };
    },
    d: (req: LoginAdminWithUserNameReqDTO, opts?: any) => {
      return {
        method: 'POST' as AllowedRequestMethod,
        url: this._uf('/api/login', {
          param: {},
          query: {},
        }),
        data: {
          username: req.username,
          password: req.password,
        },
        extraOpts: opts,
        metadata: {
          name: 'login',
          method: 'POST',
          path: '/api/login',
          req: LoginAdminWithUserNameReqDTO,
          resp: null as null,
        },
      };
    },
    e: (req: null, opts?: any) => {
      return {
        method: 'POST' as AllowedRequestMethod,
        url: this._uf('/api/logout', {
          param: {},
          query: {},
        }),
        data: {},
        extraOpts: opts,
        metadata: {
          name: 'logout',
          method: 'POST',
          path: '/api/logout',
          req: null as null,
          resp: null as null,
        },
      };
    },
    f: (req: null, opts?: any) => {
      return {
        method: 'POST' as AllowedRequestMethod,
        url: this._uf('/api/getSession', {
          param: {},
          query: {},
        }),
        data: {},
        extraOpts: opts,
        metadata: {
          name: 'getSession',
          method: 'POST',
          path: '/api/getSession',
          req: null as null,
          resp: GetSessionResDTO,
        },
      };
    },
    g: (req: UpdateAdminAvatarReqDTO, opts?: any) => {
      return {
        method: 'POST' as AllowedRequestMethod,
        url: this._uf('/api/updateAdminAvatar', {
          param: {},
          query: {},
        }),
        data: {
          avatar: req.avatar,
        },
        extraOpts: opts,
        metadata: {
          name: 'updateAdminAvatar',
          method: 'POST',
          path: '/api/updateAdminAvatar',
          req: UpdateAdminAvatarReqDTO,
          resp: null as null,
        },
      };
    },
    h: (req: null, opts?: any) => {
      return {
        method: 'POST' as AllowedRequestMethod,
        url: this._uf('/api/getAllAdmins', {
          param: {},
          query: {},
        }),
        data: {},
        extraOpts: opts,
        metadata: {
          name: 'getAllAdmins',
          method: 'POST',
          path: '/api/getAllAdmins',
          req: null as null,
          resp: GetAllAdminsListResDTO,
        },
      };
    },
    i: (req: UpdateAdminRoleReqDTO, opts?: any) => {
      return {
        method: 'POST' as AllowedRequestMethod,
        url: this._uf('/api/updateAdminRole', {
          param: {},
          query: {},
        }),
        data: {
          adminId: req.adminId,
          role: req.role,
        },
        extraOpts: opts,
        metadata: {
          name: 'updateAdminRole',
          method: 'POST',
          path: '/api/updateAdminRole',
          req: UpdateAdminRoleReqDTO,
          resp: null as null,
        },
      };
    },
    j: (req: ResetAdminPasswordReqDTO, opts?: any) => {
      return {
        method: 'POST' as AllowedRequestMethod,
        url: this._uf('/api/resetAdminPassword', {
          param: {},
          query: {},
        }),
        data: {
          adminId: req.adminId,
          newPassword: req.newPassword,
        },
        extraOpts: opts,
        metadata: {
          name: 'resetAdminPassword',
          method: 'POST',
          path: '/api/resetAdminPassword',
          req: ResetAdminPasswordReqDTO,
          resp: null as null,
        },
      };
    },
    k: (req: DeleteAdminReqDTO, opts?: any) => {
      return {
        method: 'POST' as AllowedRequestMethod,
        url: this._uf('/api/deleteAdmin', {
          param: {},
          query: {},
        }),
        data: {
          adminId: req.adminId,
        },
        extraOpts: opts,
        metadata: {
          name: 'deleteAdmin',
          method: 'POST',
          path: '/api/deleteAdmin',
          req: DeleteAdminReqDTO,
          resp: null as null,
        },
      };
    },
    l: (req: DemoGetReqDTO, opts?: any) => {
      return {
        method: 'GET' as AllowedRequestMethod,
        url: this._uf('/api/demoGet/:id', {
          param: {
            id: req.id,
          },
          query: {
            page: req.page,
          },
        }),
        data: {},
        extraOpts: opts,
        metadata: {
          name: 'demoGet',
          method: 'GET',
          path: '/api/demoGet/:id',
          req: DemoGetReqDTO,
          resp: DemoGetRespDTO,
        },
      };
    },
    m: (req: null, opts?: any) => {
      return {
        method: 'POST' as AllowedRequestMethod,
        url: this._uf('/api/getHomeData', {
          param: {},
          query: {},
        }),
        data: {},
        extraOpts: opts,
        metadata: {
          name: 'getHomeData',
          method: 'POST',
          path: '/api/getHomeData',
          req: null as null,
          resp: GetHomeDataResDTO,
        },
      };
    },
    n: (req: null, opts?: any) => {
      return {
        method: 'POST' as AllowedRequestMethod,
        url: this._uf('/api/getHomeNews', {
          param: {},
          query: {},
        }),
        data: {},
        extraOpts: opts,
        metadata: {
          name: 'getHomeNews',
          method: 'POST',
          path: '/api/getHomeNews',
          req: null as null,
          resp: GetHomeNewsResDTO,
        },
      };
    },
    o: (req: GetMediaListReqDTO, opts?: any) => {
      return {
        method: 'POST' as AllowedRequestMethod,
        url: this._uf('/api/getMediaList', {
          param: {},
          query: {},
        }),
        data: {
          type: req.type,
          page: req.page,
          pageSize: req.pageSize,
        },
        extraOpts: opts,
        metadata: {
          name: 'getMediaList',
          method: 'POST',
          path: '/api/getMediaList',
          req: GetMediaListReqDTO,
          resp: GetMediaListResDTO,
        },
      };
    },
    p: (req: UploadMediaReqDTO, opts?: any) => {
      const formData = new FormData();
      formData.append('file', req.file);
      formData.append('type', req.type);
      formData.append('alt', req.alt);
      return {
        method: 'POST' as AllowedRequestMethod,
        url: this._uf('/api/uploadMedia', {
          param: {},
          query: {},
        }),
        data: formData,
        headers: {
          'Content-Type': 'multipart/form-data',
        },
        extraOpts: opts,
        metadata: {
          name: 'uploadMedia',
          method: 'POST',
          path: '/api/uploadMedia',
          req: UploadMediaReqDTO,
          resp: MediaDetailResDTO,
        },
      };
    },
    q: (req: GetMediaByIdReqDTO, opts?: any) => {
      return {
        method: 'POST' as AllowedRequestMethod,
        url: this._uf('/api/getMediaById', {
          param: {},
          query: {},
        }),
        data: {
          id: req.id,
        },
        extraOpts: opts,
        metadata: {
          name: 'getMediaById',
          method: 'POST',
          path: '/api/getMediaById',
          req: GetMediaByIdReqDTO,
          resp: MediaDetailResDTO,
        },
      };
    },
    r: (req: UpdateMediaReqDTO, opts?: any) => {
      return {
        method: 'POST' as AllowedRequestMethod,
        url: this._uf('/api/updateMedia', {
          param: {},
          query: {},
        }),
        data: {
          id: req.id,
          alt: req.alt,
        },
        extraOpts: opts,
        metadata: {
          name: 'updateMedia',
          method: 'POST',
          path: '/api/updateMedia',
          req: UpdateMediaReqDTO,
          resp: null as null,
        },
      };
    },
    s: (req: DeleteMediaReqDTO, opts?: any) => {
      return {
        method: 'POST' as AllowedRequestMethod,
        url: this._uf('/api/deleteMedia', {
          param: {},
          query: {},
        }),
        data: {
          id: req.id,
        },
        extraOpts: opts,
        metadata: {
          name: 'deleteMedia',
          method: 'POST',
          path: '/api/deleteMedia',
          req: DeleteMediaReqDTO,
          resp: null as null,
        },
      };
    },
    t: (req: InitChunkUploadReqDTO, opts?: any) => {
      return {
        method: 'POST' as AllowedRequestMethod,
        url: this._uf('/api/initChunkUpload', {
          param: {},
          query: {},
        }),
        data: {
          filename: req.filename,
          fileSize: req.fileSize,
          type: req.type,
          alt: req.alt,
          totalChunks: req.totalChunks,
        },
        extraOpts: opts,
        metadata: {
          name: 'initChunkUpload',
          method: 'POST',
          path: '/api/initChunkUpload',
          req: InitChunkUploadReqDTO,
          resp: InitChunkUploadResDTO,
        },
      };
    },
    u: (req: UploadChunkReqDTO, opts?: any) => {
      const formData = new FormData();
      formData.append('uploadId', req.uploadId);
      formData.append('chunkIndex', req.chunkIndex);
      formData.append('chunk', req.chunk);
      return {
        method: 'POST' as AllowedRequestMethod,
        url: this._uf('/api/uploadChunk', {
          param: {},
          query: {},
        }),
        data: formData,
        headers: {
          'Content-Type': 'multipart/form-data',
        },
        extraOpts: opts,
        metadata: {
          name: 'uploadChunk',
          method: 'POST',
          path: '/api/uploadChunk',
          req: UploadChunkReqDTO,
          resp: UploadChunkResDTO,
        },
      };
    },
    v: (req: CompleteChunkUploadReqDTO, opts?: any) => {
      return {
        method: 'POST' as AllowedRequestMethod,
        url: this._uf('/api/completeChunkUpload', {
          param: {},
          query: {},
        }),
        data: {
          uploadId: req.uploadId,
        },
        extraOpts: opts,
        metadata: {
          name: 'completeChunkUpload',
          method: 'POST',
          path: '/api/completeChunkUpload',
          req: CompleteChunkUploadReqDTO,
          resp: CompleteChunkUploadResDTO,
        },
      };
    },
    w: (req: CreateNewsReqDTO, opts?: any) => {
      return {
        method: 'POST' as AllowedRequestMethod,
        url: this._uf('/api/createNews', {
          param: {},
          query: {},
        }),
        data: {
          title: req.title,
          summary: req.summary,
          content: req.content,
          coverImage: req.coverImage,
          isPublished: req.isPublished,
        },
        extraOpts: opts,
        metadata: {
          name: 'createNews',
          method: 'POST',
          path: '/api/createNews',
          req: CreateNewsReqDTO,
          resp: null as null,
        },
      };
    },
    x: (req: UpdateNewsReqDTO, opts?: any) => {
      return {
        method: 'POST' as AllowedRequestMethod,
        url: this._uf('/api/updateNews', {
          param: {},
          query: {},
        }),
        data: {
          id: req.id,
          title: req.title,
          summary: req.summary,
          content: req.content,
          coverImage: req.coverImage,
          isPublished: req.isPublished,
        },
        extraOpts: opts,
        metadata: {
          name: 'updateNews',
          method: 'POST',
          path: '/api/updateNews',
          req: UpdateNewsReqDTO,
          resp: null as null,
        },
      };
    },
    y: (req: DeleteNewsReqDTO, opts?: any) => {
      return {
        method: 'POST' as AllowedRequestMethod,
        url: this._uf('/api/deleteNews', {
          param: {},
          query: {},
        }),
        data: {
          id: req.id,
        },
        extraOpts: opts,
        metadata: {
          name: 'deleteNews',
          method: 'POST',
          path: '/api/deleteNews',
          req: DeleteNewsReqDTO,
          resp: null as null,
        },
      };
    },
    z: (req: GetNewsReqDTO, opts?: any) => {
      return {
        method: 'POST' as AllowedRequestMethod,
        url: this._uf('/api/getNews', {
          param: {},
          query: {},
        }),
        data: {
          id: req.id,
        },
        extraOpts: opts,
        metadata: {
          name: 'getNews',
          method: 'POST',
          path: '/api/getNews',
          req: GetNewsReqDTO,
          resp: GetNewsDetailResDTO,
        },
      };
    },
    aa: (req: GetNewsReqDTO, opts?: any) => {
      return {
        method: 'POST' as AllowedRequestMethod,
        url: this._uf('/api/getPublishedNews', {
          param: {},
          query: {},
        }),
        data: {
          id: req.id,
        },
        extraOpts: opts,
        metadata: {
          name: 'getPublishedNews',
          method: 'POST',
          path: '/api/getPublishedNews',
          req: GetNewsReqDTO,
          resp: GetNewsDetailResDTO,
        },
      };
    },
    ab: (req: GetAllNewsReqDTO, opts?: any) => {
      return {
        method: 'POST' as AllowedRequestMethod,
        url: this._uf('/api/getAllNews', {
          param: {},
          query: {},
        }),
        data: {
          page: req.page,
          pageSize: req.pageSize,
        },
        extraOpts: opts,
        metadata: {
          name: 'getAllNews',
          method: 'POST',
          path: '/api/getAllNews',
          req: GetAllNewsReqDTO,
          resp: GetAllNewsResDTO,
        },
      };
    },
    ac: (req: GetPublishedNewsListReqDTO, opts?: any) => {
      return {
        method: 'POST' as AllowedRequestMethod,
        url: this._uf('/api/getPublishedNewsList', {
          param: {},
          query: {},
        }),
        data: {
          page: req.page,
          pageSize: req.pageSize,
        },
        extraOpts: opts,
        metadata: {
          name: 'getPublishedNewsList',
          method: 'POST',
          path: '/api/getPublishedNewsList',
          req: GetPublishedNewsListReqDTO,
          resp: GetPublishedNewsListResDTO,
        },
      };
    },
    ad: (req: CreateProjectReqDTO, opts?: any) => {
      return {
        method: 'POST' as AllowedRequestMethod,
        url: this._uf('/api/createProject', {
          param: {},
          query: {},
        }),
        data: {
          name: req.name,
          description: req.description,
          repoUrl: req.repoUrl,
          websiteUrl: req.websiteUrl,
          coverImage: req.coverImage,
          bgColor: req.bgColor,
          isFeatured: req.isFeatured,
        },
        extraOpts: opts,
        metadata: {
          name: 'createProject',
          method: 'POST',
          path: '/api/createProject',
          req: CreateProjectReqDTO,
          resp: null as null,
        },
      };
    },
    ae: (req: UpdateProjectReqDTO, opts?: any) => {
      return {
        method: 'POST' as AllowedRequestMethod,
        url: this._uf('/api/updateProject', {
          param: {},
          query: {},
        }),
        data: {
          id: req.id,
          name: req.name,
          description: req.description,
          repoUrl: req.repoUrl,
          websiteUrl: req.websiteUrl,
          coverImage: req.coverImage,
          bgColor: req.bgColor,
          isFeatured: req.isFeatured,
        },
        extraOpts: opts,
        metadata: {
          name: 'updateProject',
          method: 'POST',
          path: '/api/updateProject',
          req: UpdateProjectReqDTO,
          resp: null as null,
        },
      };
    },
    af: (req: DeleteProjectReqDTO, opts?: any) => {
      return {
        method: 'POST' as AllowedRequestMethod,
        url: this._uf('/api/deleteProject', {
          param: {},
          query: {},
        }),
        data: {
          id: req.id,
        },
        extraOpts: opts,
        metadata: {
          name: 'deleteProject',
          method: 'POST',
          path: '/api/deleteProject',
          req: DeleteProjectReqDTO,
          resp: null as null,
        },
      };
    },
    ag: (req: GetProjectReqDTO, opts?: any) => {
      return {
        method: 'POST' as AllowedRequestMethod,
        url: this._uf('/api/getProject', {
          param: {},
          query: {},
        }),
        data: {
          id: req.id,
        },
        extraOpts: opts,
        metadata: {
          name: 'getProject',
          method: 'POST',
          path: '/api/getProject',
          req: GetProjectReqDTO,
          resp: GetProjectDetailResDTO,
        },
      };
    },
    ah: (req: GetAllProjectsReqDTO, opts?: any) => {
      return {
        method: 'POST' as AllowedRequestMethod,
        url: this._uf('/api/getAllProjects', {
          param: {},
          query: {},
        }),
        data: {
          page: req.page,
          pageSize: req.pageSize,
        },
        extraOpts: opts,
        metadata: {
          name: 'getAllProjects',
          method: 'POST',
          path: '/api/getAllProjects',
          req: GetAllProjectsReqDTO,
          resp: GetAllProjectsResDTO,
        },
      };
    },
    ai: (req: null, opts?: any) => {
      return {
        method: 'POST' as AllowedRequestMethod,
        url: this._uf('/api/getOverviewStats', {
          param: {},
          query: {},
        }),
        data: {},
        extraOpts: opts,
        metadata: {
          name: 'getOverviewStats',
          method: 'POST',
          path: '/api/getOverviewStats',
          req: null as null,
          resp: GetOverviewStatsResDTO,
        },
      };
    },
    aj: (req: GetDailyViewStatsReqDTO, opts?: any) => {
      return {
        method: 'POST' as AllowedRequestMethod,
        url: this._uf('/api/getDailyViewStats', {
          param: {},
          query: {},
        }),
        data: {
          pageKey: req.pageKey,
          days: req.days,
        },
        extraOpts: opts,
        metadata: {
          name: 'getDailyViewStats',
          method: 'POST',
          path: '/api/getDailyViewStats',
          req: GetDailyViewStatsReqDTO,
          resp: GetDailyViewStatsResDTO,
        },
      };
    },
    ak: (req: null, opts?: any) => {
      return {
        method: 'POST' as AllowedRequestMethod,
        url: this._uf('/api/getAllPageViewStats', {
          param: {},
          query: {},
        }),
        data: {},
        extraOpts: opts,
        metadata: {
          name: 'getAllPageViewStats',
          method: 'POST',
          path: '/api/getAllPageViewStats',
          req: null as null,
          resp: GetAllPageViewStatsResDTO,
        },
      };
    },
  }

  private _uf(url: string, extra: { param?: object; query?: object } = {}): string {
    const { param, query } = extra;
    return urlcat(url, {
      ...param,
      ...query,
    });
  }
}
