/**
 * This file was automatically generated by `bwcx-client-vue`.
 * DO NOT MODIFY IT BY HAND.
 */

import '@vue/runtime-core';
import { BwcxVueRouterActions } from 'bwcx-client-vue3';
import * as R from '../../common/router/client-routes';

declare module '@vue/runtime-core' {
  export interface ComponentCustomProperties {
    $$router: {
      to(target: 'About'): BwcxVueRouterActions;
      to(target: 'AdminView'): BwcxVueRouterActions;
      to(target: 'GlobalConfigView'): BwcxVueRouterActions;
      to(target: 'MediaListContainer'): BwcxVueRouterActions;
      to(target: 'NewsListContainer'): BwcxVueRouterActions;
      to(target: 'NewsPreviewView'): BwcxVueRouterActions;
      to(target: 'OverviewView'): BwcxVueRouterActions;
      to(target: 'ProjectListContainer'): BwcxVueRouterActions;
      to(target: 'UsersAdminView'): BwcxVueRouterActions;
      to(target: 'DemoDetail'): BwcxVueRouterActions<R.DemoDetailRPO>;
      to(target: 'HomeView'): BwcxVueRouterActions;
      to(target: 'LoginView'): BwcxVueRouterActions;
      to(target: 'NewsDetailView'): BwcxVueRouterActions;
      to(target: 'NewsListView'): BwcxVueRouterActions;
      to(target: 'NewsView'): BwcxVueRouterActions;
      to(target: 'AuditLogContainer'): BwcxVueRouterActions;
    };
  }
}
